// This schema.rs was auto generated by the convex-typegen crate. Modify at your own risk.
// For more information, visit https://github.com/ThatGuyJamal/convex-typegen

pub enum Users
{
    Create,
    Find,
}

impl Users
{
    pub fn to_string(&self) -> &'static str
    {
        match self {
            Users::Create => "users:create",
            Users::Find => "users:find",
        }
    }
    pub fn from_string(s: &str) -> Option<Self>
    {
        match s {
            "users:create" => Some(Users::Create),
            "users:find" => Some(Users::Find),
            _ => None,
        }
    }
}
pub enum Post
{
    Create,
    Find,
}

impl Post
{
    pub fn to_string(&self) -> &'static str
    {
        match self {
            Post::Create => "post:create",
            Post::Find => "post:find",
        }
    }
    pub fn from_string(s: &str) -> Option<Self>
    {
        match s {
            "post:create" => Some(Post::Create),
            "post:find" => Some(Post::Find),
            _ => None,
        }
    }
}
